### ISSUE TITLE
[getObjectView] ERROR: TypeError: Cannot read properties of null (reading 'root')

### ISSUE THREAD

**Issue by Lucky-ESA** [ioBroker/ioBroker.socket-classes#37]
**Describe the bug**  
Retrieve object with getExtendableInstances without response
Missing -> system.adapter.socketio
Missing -> system.adapter.ws

The following function also does not provide any data for these objects
```
        this.getForeignObjectAsync
        this.getForeignObject
        this.getObjectListAsync
        this.getObjectViewAsync(`system.adapter.socketio`)
        this.getObjectView
```

**To Reproduce**  
1. Start function -> getExtendableInstances
2. Response -> []
3. Error Log (see Logfiles)

**Expected behavior**  

**Screenshots & Logfiles**  
```
admin.0 | 2024-06-26 21:31:08.185 | info | <== Disconnect system.user.admin from ::ffff:192.168.2.164
admin.0 | 2024-06-26 21:31:08.185 | info | <== Disconnect system.user.admin from ::ffff:192.168.2.164
admin.0 | 2024-06-26 21:31:06.277 | error | [getObjectView] ERROR: TypeError: Cannot read properties of null (reading 'root')
admin.0 | 2024-06-26 21:31:06.085 | info | ==> Connected system.user.admin from ::ffff:192.168.2.164
admin.0 | 2024-06-26 21:31:05.111 | info | <== Disconnect system.user.admin from ::ffff:192.168.2.164
```

**Versions:**  
 - Adapter version: 7.0.6
 - JS-Controller version: 6.0.5
 - Node version: 20.14.0
 - Operating system: Debian version: 12 (bookworm)

**Additional context**  
Issues iqontrol adapter

**Comment by Apollon77** [comment]
check nrwest admin 7.0.7 and others, should be fixed

**Comment by Apollon77** [comment]
gtreat, could I ask you to comment the relevant iqontrol issues please too and maybe in forum to "spread the word" ? ;-)

**Comment by greatfireball** [comment]
Already done ;)

**Comment by Apollon77** [comment]
Thank you very much
