### ISSUE TITLE
Unable to delete objects with 0.5.4 (via admin or javascript adapter)

### ISSUE THREAD

**Issue by klein0r** [ioBroker/ioBroker.socket-classes#7]
Diff https://github.com/ioBroker/ioBroker.socket-classes/compare/v0.5.3...v0.5.4

see also https://github.com/ioBroker/ioBroker.javascript/issues/1151

----

With version 0.5.3 (and current admin 6.2.22):

<img width="344" alt="Screenshot 2022-10-04 at 13 21 31" src="https://user-images.githubusercontent.com/1959049/193810186-70a2082c-6658-44f3-9325-f3cc98b360eb.png">

With version 0.5.4 (and current admin 6.2.22):

<img width="432" alt="Screenshot 2022-10-04 at 13 21 05" src="https://user-images.githubusercontent.com/1959049/193810217-e45fc21c-5b56-40e1-be6c-651be5c53d44.png">

**Comment by Apollon77** [comment]
I assumed it to be here

**Comment by ftrueck** [comment]
delObject allows only flot. objects to be deleted. This could be an issue.

**Comment by Apollon77** [comment]
@ftrueck no idea where you have that idea from, but no this is not the reason

**Comment by GermanBluefox** [comment]
Should be fixed in 1.0.1
